services:
  app:
    build:
      context: service
      dockerfile: Dockerfile
    container_name: service
    env_file:
      - .env.local
    ports:
      - "${APP_HOST}:${APP_PORT}:${APP_PORT}"
    depends_on:
      mongos:
        condition: service_healthy
      redis_db:
        condition: service_started
      cassandra:
        condition: service_healthy
    restart: unless-stopped

  redis_db:
    image: redis:8.6.1-alpine
    container_name: ${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped

  cassandra:
    image: cassandra:5.0
    container_name: ${CASSANDRA_HOSTS}
    ports:
      - "${CASSANDRA_PORT}:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=NDBX_Cluster
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -E '^UN\\s' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  cfg-1:
    image: mongo:7.0
    container_name: cfg-1
    command: mongod --configsvr --replSet cfg-rs --port ${MONGODB_PORT} --bind_ip_all
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "${MONGODB_PORT}", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5

  shard-1-a:
    image: mongo:7.0
    container_name: shard-1-a
    command: mongod --shardsvr --replSet shard-1-rs --port ${MONGODB_PORT} --bind_ip_all
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "${MONGODB_PORT}", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5

  shard-1-b:
    image: mongo:7.0
    container_name: shard-1-b
    command: mongod --shardsvr --replSet shard-1-rs --port ${MONGODB_PORT} --bind_ip_all

  shard-1-c:
    image: mongo:7.0
    container_name: shard-1-c
    command: mongod --shardsvr --replSet shard-1-rs --port ${MONGODB_PORT} --bind_ip_all

  shard-2-a:
    image: mongo:7.0
    container_name: shard-2-a
    command: mongod --shardsvr --replSet shard-2-rs --port ${MONGODB_PORT} --bind_ip_all
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "${MONGODB_PORT}", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5

  shard-2-b:
    image: mongo:7.0
    container_name: shard-2-b
    command: mongod --shardsvr --replSet shard-2-rs --port ${MONGODB_PORT} --bind_ip_all

  shard-2-c:
    image: mongo:7.0
    container_name: shard-2-c
    command: mongod --shardsvr --replSet shard-2-rs --port ${MONGODB_PORT} --bind_ip_all

  mongos:
    image: mongo:7.0
    container_name: ${MONGODB_HOST}
    command: mongos --configdb cfg-rs/cfg-1:${MONGODB_PORT} --port ${MONGODB_PORT} --bind_ip_all
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    depends_on:
      cfg-1:
        condition: service_healthy
      shard-1-a:
        condition: service_healthy
      shard-2-a:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "${MONGODB_PORT}", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-init:
    image: mongo:7.0
    container_name: mongo-init
    env_file:
      - .env.local
    volumes:
      - ./init-shard.sh:/init-shard.sh
    entrypoint: [ "/bin/bash", "/init-shard.sh" ]
    depends_on:
      - mongos
      - cfg-1
      - shard-1-a
      - shard-2-a
