services:
  app:
    build:
      context: ./lab01
      dockerfile: Dockerfile

    container_name: lab01

    env_file:
      - .env.local

    hostname: "${APP_HOST}"
    ports:
      - "${APP_PORT}:${APP_PORT}"

    restart: unless-stopped
