services:
  app:
    build:
      context: service
      dockerfile: Dockerfile
    container_name: service
    env_file:
      - .env.local
    ports:
      - "${APP_HOST}:${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis_db
      - mongodb
    restart: unless-stopped

  redis_db:
    image: redis:8.6.1-alpine
    container_name: ${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped
#    command: redis-server --requirepass ${REDIS_PASSWORD}

  mongodb:
    image: mongo:7.0
    container_name: ${MONGODB_HOST}
    restart: unless-stopped
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    env_file:
      - .env.local
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
#      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
